export const tokenList = [
    { 
        name:'WTRX',
        address:'TGky6zKfhrisXh92emTvPAbkenhXHTU8m6',
        img:'111',
        balance:0,
        decimals:18
    },
    { 
        name:'inverst',
        address:'TNFjWx7h4X9LqGcfJumnTsKDdzN1ePvQ5C',
        img:'',
        balance:0,
        decimals:18
    },
    { 
        name:'DAI',
        address:'TDFPVQJQnYFZrw1SvxKBsc34i9xiSe73bq',
        img:'',
        balance:0,
        decimals:18
    },
    { 
        name:'USDT',
        address:'TBKYAnVJdKWUJLdTYHuy1mmoL9ifYWTSAU',
        img:'',
        balance:0,
        decimals:18
    },
    { 
        name:'LOM1',
        address:'TC4cWgq9FvXrM3vgyUdyexQDrbPUD3tpNa',
        img:'',
        balance:0,
        decimals:18
    },
    { 
        name:'SPKL',
        address:'TSdqRcnAaMUQWRy4zRR8Pd3QuJuBKX9W55',
        img:'',
        balance:0,
        decimals:18
    }
]
export const pairList = [
    {
        address:'TVQpB9Eh66hua8VKNoq3oGt6SacSbXzWk9',
        token1:'WTRX',
        token2:'inverst',
        pair:'WTRX/INVERST',
        decimals:18
    },
    {
        address:'TRoaUkGQzqnPuEMvNBN2FrciJDLQ7T7mJe',
        token1:'WTRX',
        token2:'DAI',
        pair:'WTRX/DAI',
        decimals:18
    }
]

const tokenData = {
    tokenList,
    pairList
}
export default tokenData